spring.datasource.url=jdbc:postgresql://localhost:5432/taskboard_db
spring.datasource.username=app_user
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
